### ISSUE TITLE
Formatação de CPFs e CNPJs

### ISSUE THREAD

**Issue by gustavocruzeiro** [mateuswetah/Projeto-Salic#1]
Na área "cgccpf", onde são inseridos ou CPFs ou CNPJs, sugiro que sejam formatados os resultados da seguinte maneira:

1. No caso do CPF, passe de "******00000" para "***.***.000/00".
2. No caso de CNPJ, passe de "00000000000000" para "00.000.000/0000-00".

**Comment by mateuswetah** [comment]
Pronto. A formatação pode ser feita pela função `formataCGCCPF(_cgccpf_)` do _DataFormatterService_. Há um exemplo de uso na página de projetos. 
Subirei na página até o fim do dia.
