### ISSUE TITLE
Erro na navegação de páginas Proponentes

### ISSUE THREAD

**Issue by nitaibezerra** [mateuswetah/Projeto-Salic#16]
Na consulta abaixo:
http://hmg.app.api.salic.cultura.gov.br/#/proponentes/8c2a7d0ae821b3ea79131fdc97cea1ae0cdd1613791acaf958c8bfbd1f6c 

Contabiliza 30 resultados. A primeira página exibe 12 e após clicar em “EXIBIR MAIS”, e ele exibir mais 6, o “EXIBIR MAIS” deixa de funcionar

**Comment by mateuswetah** [comment]
Mea culpa. Era um probleminha de índice. Creio que no próximo commit vai estar OK.
