### ISSUE TITLE
Apresentação de informações do Projeto

### ISSUE THREAD

**Issue by nitaibezerra** [mateuswetah/Projeto-Salic#19]
Alternar a ordem dos campos de valores de um Projeto. Hoje está assim:
![captura de tela de 2017-05-09 23-27-36](https://cloud.githubusercontent.com/assets/1244443/25880789/d5ab4d86-350f-11e7-92b1-1edbadbeba80.png)
Valor do Projeto
Valor Aprovado
Outras Fontes

Faz mas sentido ordenando da seguinte forma:
Valor Aprovado
Outras Fontes
Valor do Projeto

A relação é que o Valor do Projeto é a soma do Valor Aprovado com Outras Fontes. Inclusive incluindo uma linha e um símbolo de soma "+" podem deixar essa relação mais explícita

**Comment by mateuswetah** [comment]
Ordem trocada. 

Esse tipo de conhecimento ajuda mesmo a tomar umas decisões melhores de Design. Acho que até foi comentada essa possibilidade da soma quando estávamos pensando nessa página. A questão é que ficava um pouco estranho colocar o símbolo de soma e a barra envolvidos só nestes valores da direita e não fazer nada com os da esquerda. Existe uma relação do tipo entre Valor Proposta, Valor Captado e Valor Solicitado?

**Comment by nitaibezerra** [comment]
Fiquei em dúvida sobre a diferença entre valor solicitado e valor proposta.

Lembrei que, na tela de listagem da consulta por projeto, em cada projeto, aparecem o valor do projeto e o valor captado. Acontece que o valor do projeto fica zerado para os projetos muito recentes (primeiros com a consulta padrão), que acabaram de ser aceitos mas ainda sem o valor aprovado/projeto definido. Acho que fica mais interessante incluir o Valor proposta tb. Se acharem que 3 informações é muito, pro espaço, então sugiro manterem Valor Proposta e Valor Captado

**Comment by mateuswetah** [comment]
Certo, concordo. 
Coloquei **Valor Proposta** no lugar do **Valor Projeto** porque acho que o card já está muito denso e mecher com a altura dele agora poderia quebrar uns detalhes no layout mais complicadinhos de arrumar...

No proximo commit estará atualizado.
