### ISSUE TITLE
Célula Excel com limitação de caracteres

### ISSUE THREAD

**Issue by amaral008** [mateuswetah/Projeto-Salic#28]
Prezado Mateus,
Quando eu subo os dados em .csv no Excel, ele restringe o texto das células na maioria das colunas a 200 caracteres, interrompendo o texto. Isto acontece em UTF-8, ou qualquer outro tipo de configuração do texto.
Grato por qualquer orientação sobre como resolver isso.

**Comment by mateuswetah** [comment]
Olá @amaral008!

Só pra eu entender, você está exportando os dados em CSV mas eles vem limitados a 200 carácteres diretamente? Ou eles estão lá mas quando você abre pelo Excel eles são limados em 200? 

Se estiverem vindo cortados da aplicação, pode ser uma limitação da API:
https://api.salic.cultura.gov.br/doc/

**Comment by amaral008** [comment]
Boa noite, Mateus

O conteúdo está vindo cortado. Chamei os dados com diferentes
configurações, e a limitação de caracteres não desaparece.

Abraço,
Rodrigo

**Comment by mateuswetah** [comment]
É então vai ser preciso contatar o pessoal que fez a API do SALIC... eu não sei dizer com certeza nas mãos de quem isso está hoje, mas na documentação o email que está disponível é [esse](ldaufg@gmail.com). Porque este  repositório é da aplicação que consome esta API, ok?

Abraços!
