### ISSUE TITLE
Título de "Resultado" na página de resultados com chips e fixo on scroll

### ISSUE THREAD

**Issue by gustavocruzeiro** [mateuswetah/Projeto-Salic#5]
Na página de resultado de busca/filtros, o ideal seria deixar a Header fixa quando ela ficasse no topo da página, ao fazer scroll, e deixar também os chips com os filtros de pesquisa ao lado, para a fácil remoção de certos filtros durante a pesquisa.

**Comment by mateuswetah** [comment]
Implementado. Restam algumas correções de bugs e adequações ao layout oficial.
